### ISSUE TITLE
xbuilder support

### ISSUE THREAD

**Issue by a10kiloham** [hundertzehn/caddy-ratelimit#1]
Thanks for making this! How do I install? In my Dockerfile I have `RUN xcaddy build  --with github.com/caddy-dns/cloudflare github.com/hundertzehn/caddy-ratelimit` but get an error:
`2021/03/02 15:59:27 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@github.com/hundertzehn/caddy-ratelimit
go get github.com/caddyserver/caddy/v2@github.com/hundertzehn/caddy-ratelimit: github.com/caddyserver/caddy/v2@github.com/hundertzehn/caddy-ratelimit: invalid version: version "github.com/hundertzehn/caddy-ratelimit" invalid: disallowed version string`

**Comment by a10kiloham** [comment]
nevermind needs --with for each module

**Comment by pic** [comment]
yes, exactly :+1: , for example:

```
RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/hundertzehn/caddy-ratelimit@v0.0.5
```
